{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9e7d5e7b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [01/Sep/2023 20:41:19] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [01/Sep/2023 20:41:26] \"GET /apidocs HTTP/1.1\" 404 -\n",
      "127.0.0.1 - - [01/Sep/2023 20:41:39] \"GET /docs/ HTTP/1.1\" 200 -\n",
      "ERROR:root:jsonify failure; defaulting to json.dumps\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 581, in load_from_file\n",
      "    enc = detect_by_bom(swag_path)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 616, in detect_by_bom\n",
      "    with open(path, 'rb') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\iradz\\\\AppData\\\\Local\\\\Temp\\\\ipykernel_29484\\\\docs/hello_world.yml'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 590, in load_from_file\n",
      "    enc = detect_by_bom(swag_path)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 616, in detect_by_bom\n",
      "    with open(path, 'rb') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\iradz\\\\AppData\\\\Local\\\\Temp\\\\ipykernel_29484\\\\docs/hello_world.yml'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\base.py\", line 164, in get\n",
      "    return jsonify(self.loader())\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\base.py\", line 438, in get_apispecs\n",
      "    specs = get_specs(\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 180, in get_specs\n",
      "    doc_summary, doc_description, doc_swag = parse_docstring(\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 646, in parse_docstring\n",
      "    full_doc = load_from_file(swag_paths[key], swag_type)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 604, in load_from_file\n",
      "    if package_spec.has_location:\n",
      "AttributeError: 'NoneType' object has no attribute 'has_location'\n",
      "ERROR:__main__:Exception on /docs.json [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 581, in load_from_file\n",
      "    enc = detect_by_bom(swag_path)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 616, in detect_by_bom\n",
      "    with open(path, 'rb') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\iradz\\\\AppData\\\\Local\\\\Temp\\\\ipykernel_29484\\\\docs/hello_world.yml'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 590, in load_from_file\n",
      "    enc = detect_by_bom(swag_path)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 616, in detect_by_bom\n",
      "    with open(path, 'rb') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\iradz\\\\AppData\\\\Local\\\\Temp\\\\ipykernel_29484\\\\docs/hello_world.yml'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\base.py\", line 164, in get\n",
      "    return jsonify(self.loader())\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\base.py\", line 438, in get_apispecs\n",
      "    specs = get_specs(\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 180, in get_specs\n",
      "    doc_summary, doc_description, doc_swag = parse_docstring(\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 646, in parse_docstring\n",
      "    full_doc = load_from_file(swag_paths[key], swag_type)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 604, in load_from_file\n",
      "    if package_spec.has_location:\n",
      "AttributeError: 'NoneType' object has no attribute 'has_location'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 581, in load_from_file\n",
      "    enc = detect_by_bom(swag_path)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 616, in detect_by_bom\n",
      "    with open(path, 'rb') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\iradz\\\\AppData\\\\Local\\\\Temp\\\\ipykernel_29484\\\\docs/hello_world.yml'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 590, in load_from_file\n",
      "    enc = detect_by_bom(swag_path)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 616, in detect_by_bom\n",
      "    with open(path, 'rb') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\iradz\\\\AppData\\\\Local\\\\Temp\\\\ipykernel_29484\\\\docs/hello_world.yml'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flask\\views.py\", line 89, in view\n",
      "    return self.dispatch_request(*args, **kwargs)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flask\\views.py\", line 163, in dispatch_request\n",
      "    return meth(*args, **kwargs)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\base.py\", line 168, in get\n",
      "    specs = json.dumps(self.loader())\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\base.py\", line 438, in get_apispecs\n",
      "    specs = get_specs(\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 180, in get_specs\n",
      "    doc_summary, doc_description, doc_swag = parse_docstring(\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 646, in parse_docstring\n",
      "    full_doc = load_from_file(swag_paths[key], swag_type)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 604, in load_from_file\n",
      "    if package_spec.has_location:\n",
      "AttributeError: 'NoneType' object has no attribute 'has_location'\n",
      "127.0.0.1 - - [01/Sep/2023 20:41:40] \"GET /docs.json HTTP/1.1\" 500 -\n",
      "INFO:werkzeug:127.0.0.1 - - [01/Sep/2023 20:41:40] \"\u001b[35m\u001b[1mGET /docs.json HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [01/Sep/2023 20:46:01] \"GET /docs/ HTTP/1.1\" 200 -\n",
      "INFO:werkzeug:127.0.0.1 - - [01/Sep/2023 20:46:01] \"GET /docs/ HTTP/1.1\" 200 -\n",
      "ERROR:root:jsonify failure; defaulting to json.dumps\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 581, in load_from_file\n",
      "    enc = detect_by_bom(swag_path)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 616, in detect_by_bom\n",
      "    with open(path, 'rb') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\iradz\\\\AppData\\\\Local\\\\Temp\\\\ipykernel_29484\\\\docs/hello_world.yml'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 590, in load_from_file\n",
      "    enc = detect_by_bom(swag_path)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 616, in detect_by_bom\n",
      "    with open(path, 'rb') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\iradz\\\\AppData\\\\Local\\\\Temp\\\\ipykernel_29484\\\\docs/hello_world.yml'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\base.py\", line 164, in get\n",
      "    return jsonify(self.loader())\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\base.py\", line 438, in get_apispecs\n",
      "    specs = get_specs(\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 180, in get_specs\n",
      "    doc_summary, doc_description, doc_swag = parse_docstring(\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 646, in parse_docstring\n",
      "    full_doc = load_from_file(swag_paths[key], swag_type)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 604, in load_from_file\n",
      "    if package_spec.has_location:\n",
      "AttributeError: 'NoneType' object has no attribute 'has_location'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:__main__:Exception on /docs.json [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 581, in load_from_file\n",
      "    enc = detect_by_bom(swag_path)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 616, in detect_by_bom\n",
      "    with open(path, 'rb') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\iradz\\\\AppData\\\\Local\\\\Temp\\\\ipykernel_29484\\\\docs/hello_world.yml'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 590, in load_from_file\n",
      "    enc = detect_by_bom(swag_path)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 616, in detect_by_bom\n",
      "    with open(path, 'rb') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\iradz\\\\AppData\\\\Local\\\\Temp\\\\ipykernel_29484\\\\docs/hello_world.yml'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\base.py\", line 164, in get\n",
      "    return jsonify(self.loader())\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\base.py\", line 438, in get_apispecs\n",
      "    specs = get_specs(\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 180, in get_specs\n",
      "    doc_summary, doc_description, doc_swag = parse_docstring(\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 646, in parse_docstring\n",
      "    full_doc = load_from_file(swag_paths[key], swag_type)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 604, in load_from_file\n",
      "    if package_spec.has_location:\n",
      "AttributeError: 'NoneType' object has no attribute 'has_location'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 581, in load_from_file\n",
      "    enc = detect_by_bom(swag_path)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 616, in detect_by_bom\n",
      "    with open(path, 'rb') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\iradz\\\\AppData\\\\Local\\\\Temp\\\\ipykernel_29484\\\\docs/hello_world.yml'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 590, in load_from_file\n",
      "    enc = detect_by_bom(swag_path)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 616, in detect_by_bom\n",
      "    with open(path, 'rb') as f:\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\iradz\\\\AppData\\\\Local\\\\Temp\\\\ipykernel_29484\\\\docs/hello_world.yml'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flask\\views.py\", line 89, in view\n",
      "    return self.dispatch_request(*args, **kwargs)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flask\\views.py\", line 163, in dispatch_request\n",
      "    return meth(*args, **kwargs)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\base.py\", line 168, in get\n",
      "    specs = json.dumps(self.loader())\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\base.py\", line 438, in get_apispecs\n",
      "    specs = get_specs(\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 180, in get_specs\n",
      "    doc_summary, doc_description, doc_swag = parse_docstring(\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 646, in parse_docstring\n",
      "    full_doc = load_from_file(swag_paths[key], swag_type)\n",
      "  File \"C:\\Users\\iradz\\anaconda3\\lib\\site-packages\\flasgger\\utils.py\", line 604, in load_from_file\n",
      "    if package_spec.has_location:\n",
      "AttributeError: 'NoneType' object has no attribute 'has_location'\n",
      "127.0.0.1 - - [01/Sep/2023 20:46:01] \"GET /docs.json HTTP/1.1\" 500 -\n",
      "INFO:werkzeug:127.0.0.1 - - [01/Sep/2023 20:46:01] \"\u001b[35m\u001b[1mGET /docs.json HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [01/Sep/2023 20:46:01] \"GET /flasgger_static/favicon-32x32.png HTTP/1.1\" 200 -\n",
      "INFO:werkzeug:127.0.0.1 - - [01/Sep/2023 20:46:01] \"GET /flasgger_static/favicon-32x32.png HTTP/1.1\" 200 -\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "# Import library for Flask\n",
    "from flask import Flask, jsonify, request\n",
    "from flasgger import Swagger, LazyString, LazyJSONEncoder\n",
    "from flasgger import swag_from\n",
    "\n",
    "\n",
    "# Define Swagger UI description\n",
    "app = Flask(__name__)\n",
    "app.json_encoder = LazyJSONEncoder\n",
    "swagger_template = dict(\n",
    "info = {\n",
    "    'title': LazyString(lambda: 'API Documentation for Data Processing and Modeling'),\n",
    "    'version': LazyString(lambda: '1.0.0'),\n",
    "    'description': LazyString(lambda: 'Dokumentasi API untuk Data Processing dan Modeling'),\n",
    "    },\n",
    "    host = LazyString(lambda: request.host)\n",
    ")\n",
    "swagger_config = {\n",
    "    \"headers\": [],\n",
    "    \"specs\": [\n",
    "        {\n",
    "            \"endpoint\": 'docs',\n",
    "            \"route\": '/docs.json',\n",
    "        }\n",
    "    ],\n",
    "    \"static_url_path\": \"/flasgger_static\",\n",
    "    \"swagger_ui\": True,\n",
    "    \"specs_route\": \"/docs/\"\n",
    "}\n",
    "swagger = Swagger(app, template=swagger_template,             \n",
    "                  config=swagger_config)\n",
    "\n",
    "# Define endpoint for \"input teks via form\"\n",
    "@swag_from(\"docs/hello_world.yml\", methods=['GET'])\n",
    "@app.route('/', methods=['GET'])\n",
    "def hello_world():\n",
    "    json_response = {\n",
    "        'status_code': 200,\n",
    "        'description': \"Menyapa Hello World\",\n",
    "        'data': \"Hello World\",\n",
    "    }\n",
    "    response_data = jsonify(json_response)\n",
    "    return response_data\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    app.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "43204def",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'0.9.7b2'"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import flasgger\n",
    "flasgger.__version__"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "02bd4b8f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'1.1.2'"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import flask\n",
    "flask.__version__"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "22d237c6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
